apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bank.ceecloudtech.online
    - bankapi.ceecloudtech.online
    secretName: bank-tls-secret
  rules:
  - host: bank.ceecloudtech.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-frontend-service
            port:
              number: 3000
  - host: bankapi.ceecloudtech.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-backend-service
            port:
              number: 8080
