apiVersion: v1
kind: Service
metadata:
  name: bank-frontend-service
spec:
  selector:
    app: frontend-banking-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 
